# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-13 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'Lewis Peaty', b'Lewis')], default=b'Lewis Peaty', max_length=30, verbose_name=b'your name')),
                ('time_stamp', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=b'time stamp')),
                ('n_exercises', models.IntegerField(default=4, verbose_name=b'number of exercises performed')),
                ('avg_sets', models.IntegerField(default=4, verbose_name=b'average sets per exericse')),
                ('workout', models.CharField(choices=[(b'ARM', b'Arms'), (b'LEG', b'Legs'), (b'SHL', b'Shoulders'), (b'COR', b'Core'), (b'BCK', b'Back'), (b'BNB', b'BitsNBobs'), (b'CUS', b'Custom'), (b'CRD', b'Cardio'), (b'CHT', b'Chest')], default=b'CUS', max_length=3)),
            ],
        ),
    ]
