# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-13 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'Lewis Peaty', b'Lewis')], default=b'Lewis Peaty', max_length=30, verbose_name=b'your name')),
                ('time_stamp', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=b'time stamp')),
                ('food', models.CharField(choices=[(b'Fruit', b'Fruit'), (b'Coffee', b'Coffee'), (b'Salad', b'Salad'), (b'Pastry', b'Pastry'), (b'Rice', b'Rice'), (b'Noodles', b'Noodles'), (b'Other', b'Other'), (b'Beer', b'Beer'), (b'Meat', b'Meat'), (b'Fish', b'Fish'), (b'Sandwich/Burger', b'Sandwich/Burger'), (b'Nuts-TrailMix', b'Nuts-TrailMix'), (b'Durian Fruit Oh No', b'Durian Fruit Oh No'), (b'Dessert', b'Dessert')], default=b'Coffee', max_length=3)),
            ],
        ),
    ]
