# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-13 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20161113_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food',
            field=models.CharField(choices=[(b'Fruit', b'Fruit'), (b'Coffee', b'Coffee'), (b'Salad', b'Salad'), (b'Pastry', b'Pastry'), (b'Rice', b'Rice'), (b'Noodles', b'Noodles'), (b'Other', b'Other'), (b'Beer', b'Beer'), (b'Meat', b'Meat'), (b'Fish', b'Fish'), (b'Sandwich/Burger', b'Sandwich/Burger'), (b'Nuts-TrailMix', b'Nuts-TrailMix'), (b'Durian Fruit Oh No', b'Durian Fruit Oh No'), (b'Dessert', b'Dessert')], default=b'Coffee', max_length=30),
        ),
    ]
